-- Deprecated compatibility pointer.
--
-- HRMS-006 replaced the manually assembled bootstrap with ordered migrations.
-- Provision a project by applying every file in supabase/migrations in filename
-- order. See docs/DATABASE_MIGRATIONS.md for commands, verification, and rollback.
